name: Release (stable)

on:
  push:
    tags:
      - "v*" # e.g. v1.0.0
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile # use your lowercase filename
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/barcode-scanner:${{ github.ref_name }}
            ghcr.io/${{ secrets.GHCR_USERNAME }}/barcode-scanner:stable
